GET https://mc.drazisil.com

###

GET https://mc.drazisil.com/favicon.ico


###

mc.drazisil.com:443/log/getAll

###

mc.drazisil.com:443/people/drazi

###

POST mc.drazisil.com:443/people/drazi/inbox
content-type: application/activity+json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}
